### PR TITLE
Update docker-compose.yml

### PR DESCRIPTION
**Pull request by oregonpillow**
default Radarr port change, for added transparency

### CODE REVIEW

**Comment by davidnewhall** [comment]
Thanks! Want to fix the others? Readarr: 8787, Lidarr: 8686

**Comment by bakerboy448** [comment]
Nitpick perhaps also update the paths to /data/downloads or /data/downloads/torrents to imply proper paths that facilitate hardlinks

**Comment by oregonpillow** [comment]
> Nitpick perhaps also update the paths to /data/downloads or /data/downloads/torrents to imply proper paths that facilitate hardlinks

do you mean correcting /downloads ? But this is correct?  By default the **internally** mapped folder that radarr/sonarr dockers use is /downloads. The external location is irrelevant since this is specified in the radarr/sonarr docker configs. E.g. within radarr docker-compose i have <my external path>:/downloads

**Comment by oregonpillow** [comment]
> Thanks! Want to fix the others? Readarr: 8787, Lidarr: 8686

done

**Comment by Roxedus** [comment]
> > Nitpick perhaps also update the paths to /data/downloads or /data/downloads/torrents to imply proper paths that facilitate hardlinks
> 
> do you mean correcting /downloads ? But this is correct? By default the **internally** mapped folder that radarr/sonarr dockers use is /downloads. The external location is irrelevant since this is specified in the radarr/sonarr docker configs. E.g. within radarr docker-compose i have `<my external path>:/downloads`

Nope, he mean /data/downloads, as per [servarr wiki](https://wiki.servarr.com/docker-guide#consistent-and-well-planned-paths)

**Comment by bakerboy448** [comment]
*arr apps do not use any path by default. The user provides the environment paths (docker mappings) and the paths themselves come from the download client's API

As Rox noted, I mean using paths per the docker guide and trash's guide that facilitate hardlinks and atomic moves rather than copies and copies + delete which use double space for seeding torrents (rar'd files not withstanding) and create unnecessary avoidable I/O use

**Comment by davidnewhall** [comment]
Setting paths to `/data/downloads` goes against everything else in this app, but I don'ts docker-compose, so meh.

**Comment by davidnewhall** [comment]
Today I removed the paths from the docker-compose example entirely. Because you shouldn't have to set paths if you mount the data in the correct location. It's an advanced config most Docker users will never need to fiddle with. Those that do can find it in the docs.

**Pull request merged**
