### PR TITLE
Create docker-compose.yml

### PR DESCRIPTION
**Pull request by maxfield-allison**
Add example docker-compose.yml

### CODE REVIEW

**Comment by maxfield-allison** [comment]
tested and working on my server

**Review by davidnewhall — CHANGES_REQUESTED** [review]
This appears to be a third place that documents all of the variables. Not entirely sure if I'm keen on that. Probably remove all the comments so I don't have to keep those up to date; add a comment at the top that links back to the repo README or example config file where these values are already documented/commented.

The compose file should go into the `init/docker/` or `examples/` folder. I'm not too picky on which one it goes in, just not the root folder.

**Comment by maxfield-allison** [comment]
updated as requested, thanks for the feedback

**Review by davidnewhall — APPROVED** [review]

**Comment by davidnewhall** [comment]
Thank you!

**Pull request merged**
